### ISSUE TITLE
raw_records causes panic at record.rs:154:22 for some files

### ISSUE THREAD

**Issue by ivan** [vv9k/mobi-rs#42]
For the five MOBI files in [mobi-rs-panic-samples.zip](https://ludios.net/tmp/mobi-rs-panic-samples.zip), calling `raw_records` results in one of these forms of panics:

```
thread 'main' panicked at 'range end index 167053 out of range for slice of length 165360', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
```

or

```
thread 'main' panicked at 'slice index starts at 1113421 but ends at 1113364', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
```

Repro:

```rust
fn main() {
    let args: Vec<_> = std::env::args().collect();
    let path = &args[1];
    let mobi = mobi::Mobi::from_path(path).unwrap();
    mobi.raw_records();
}
```

```sh
for i in mobi-rs-panic-samples/*/sample-*; do echo $i; ./target/debug/mobi-rs-panic "$i"; echo; done
```

```
mobi-rs-panic-samples/invalid-in-calibre/sample-v6.mobi
thread 'main' panicked at 'range end index 167053 out of range for slice of length 165360', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

mobi-rs-panic-samples/invalid-in-calibre/sample-v8.azw3
thread 'main' panicked at 'range end index 657829 out of range for slice of length 642619', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

mobi-rs-panic-samples/valid-in-calibre/sample-v6.mobi
thread 'main' panicked at 'range end index 729548 out of range for slice of length 727858', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

mobi-rs-panic-samples/valid-in-calibre/sample-v7.mobi
thread 'main' panicked at 'slice index starts at 1113421 but ends at 1113364', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

mobi-rs-panic-samples/valid-in-calibre/sample-v8.azw3
thread 'main' panicked at 'slice index starts at 41049289 but ends at 41047845', ~/.cargo/git/checkouts/mobi-rs-b09d3f853998f6b5/bc332dc/src/record.rs:154:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by qforce85** [comment]
My PR adds the needed bounds checks. The fix works with the mobi files provided by @ivan, as well as some of my own mobi files where mobi-rs was failing.
